server:
  port: 9090
spring:
  application:
    name: spring-cloud-eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
