server:
  port: 9092
spring:
  application:
    name: cloud-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.44.144:3306/good?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    prefer-ip-address: true
# 使用mybatis操作数据库配置以下内容
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
